#include "Riend/Interface/Wearable.h"

// 왜 얘네가 AutoGenerated 되어있지..?
//int32 IWearable::GetStrengthRequirement_Implementation()
//{
//	return 0;
//}
//
//bool IWearable::CanEquip_Implementation( APawn* Wearer )
//{
//	return true;
//}
//
